// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bt-web-ide/internal/repository/mysql/model"
)

func newUsersRegistration(db *gorm.DB, opts ...gen.DOOption) usersRegistration {
	_usersRegistration := usersRegistration{}

	_usersRegistration.usersRegistrationDo.UseDB(db, opts...)
	_usersRegistration.usersRegistrationDo.UseModel(&model.UsersRegistration{})

	tableName := _usersRegistration.usersRegistrationDo.TableName()
	_usersRegistration.ALL = field.NewAsterisk(tableName)
	_usersRegistration.ID = field.NewInt32(tableName, "id")
	_usersRegistration.Username = field.NewString(tableName, "username")
	_usersRegistration.PasswordHash = field.NewString(tableName, "password_hash")
	_usersRegistration.Email = field.NewString(tableName, "email")
	_usersRegistration.PhoneNumber = field.NewString(tableName, "phone_number")
	_usersRegistration.Role = field.NewString(tableName, "role")
	_usersRegistration.CreatedAt = field.NewTime(tableName, "created_at")
	_usersRegistration.UpdatedAt = field.NewTime(tableName, "updated_at")

	_usersRegistration.fillFieldMap()

	return _usersRegistration
}

type usersRegistration struct {
	usersRegistrationDo

	ALL          field.Asterisk
	ID           field.Int32
	Username     field.String
	PasswordHash field.String
	Email        field.String
	PhoneNumber  field.String
	Role         field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (u usersRegistration) Table(newTableName string) *usersRegistration {
	u.usersRegistrationDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u usersRegistration) As(alias string) *usersRegistration {
	u.usersRegistrationDo.DO = *(u.usersRegistrationDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *usersRegistration) updateTableName(table string) *usersRegistration {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.Username = field.NewString(table, "username")
	u.PasswordHash = field.NewString(table, "password_hash")
	u.Email = field.NewString(table, "email")
	u.PhoneNumber = field.NewString(table, "phone_number")
	u.Role = field.NewString(table, "role")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *usersRegistration) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *usersRegistration) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["username"] = u.Username
	u.fieldMap["password_hash"] = u.PasswordHash
	u.fieldMap["email"] = u.Email
	u.fieldMap["phone_number"] = u.PhoneNumber
	u.fieldMap["role"] = u.Role
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u usersRegistration) clone(db *gorm.DB) usersRegistration {
	u.usersRegistrationDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u usersRegistration) replaceDB(db *gorm.DB) usersRegistration {
	u.usersRegistrationDo.ReplaceDB(db)
	return u
}

type usersRegistrationDo struct{ gen.DO }

func (u usersRegistrationDo) Debug() *usersRegistrationDo {
	return u.withDO(u.DO.Debug())
}

func (u usersRegistrationDo) WithContext(ctx context.Context) *usersRegistrationDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u usersRegistrationDo) ReadDB() *usersRegistrationDo {
	return u.Clauses(dbresolver.Read)
}

func (u usersRegistrationDo) WriteDB() *usersRegistrationDo {
	return u.Clauses(dbresolver.Write)
}

func (u usersRegistrationDo) Session(config *gorm.Session) *usersRegistrationDo {
	return u.withDO(u.DO.Session(config))
}

func (u usersRegistrationDo) Clauses(conds ...clause.Expression) *usersRegistrationDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u usersRegistrationDo) Returning(value interface{}, columns ...string) *usersRegistrationDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u usersRegistrationDo) Not(conds ...gen.Condition) *usersRegistrationDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u usersRegistrationDo) Or(conds ...gen.Condition) *usersRegistrationDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u usersRegistrationDo) Select(conds ...field.Expr) *usersRegistrationDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u usersRegistrationDo) Where(conds ...gen.Condition) *usersRegistrationDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u usersRegistrationDo) Order(conds ...field.Expr) *usersRegistrationDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u usersRegistrationDo) Distinct(cols ...field.Expr) *usersRegistrationDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u usersRegistrationDo) Omit(cols ...field.Expr) *usersRegistrationDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u usersRegistrationDo) Join(table schema.Tabler, on ...field.Expr) *usersRegistrationDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u usersRegistrationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *usersRegistrationDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u usersRegistrationDo) RightJoin(table schema.Tabler, on ...field.Expr) *usersRegistrationDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u usersRegistrationDo) Group(cols ...field.Expr) *usersRegistrationDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u usersRegistrationDo) Having(conds ...gen.Condition) *usersRegistrationDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u usersRegistrationDo) Limit(limit int) *usersRegistrationDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u usersRegistrationDo) Offset(offset int) *usersRegistrationDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u usersRegistrationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *usersRegistrationDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u usersRegistrationDo) Unscoped() *usersRegistrationDo {
	return u.withDO(u.DO.Unscoped())
}

func (u usersRegistrationDo) Create(values ...*model.UsersRegistration) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u usersRegistrationDo) CreateInBatches(values []*model.UsersRegistration, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u usersRegistrationDo) Save(values ...*model.UsersRegistration) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u usersRegistrationDo) First() (*model.UsersRegistration, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersRegistration), nil
	}
}

func (u usersRegistrationDo) Take() (*model.UsersRegistration, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersRegistration), nil
	}
}

func (u usersRegistrationDo) Last() (*model.UsersRegistration, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersRegistration), nil
	}
}

func (u usersRegistrationDo) Find() ([]*model.UsersRegistration, error) {
	result, err := u.DO.Find()
	return result.([]*model.UsersRegistration), err
}

func (u usersRegistrationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UsersRegistration, err error) {
	buf := make([]*model.UsersRegistration, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u usersRegistrationDo) FindInBatches(result *[]*model.UsersRegistration, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u usersRegistrationDo) Attrs(attrs ...field.AssignExpr) *usersRegistrationDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u usersRegistrationDo) Assign(attrs ...field.AssignExpr) *usersRegistrationDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u usersRegistrationDo) Joins(fields ...field.RelationField) *usersRegistrationDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u usersRegistrationDo) Preload(fields ...field.RelationField) *usersRegistrationDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u usersRegistrationDo) FirstOrInit() (*model.UsersRegistration, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersRegistration), nil
	}
}

func (u usersRegistrationDo) FirstOrCreate() (*model.UsersRegistration, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersRegistration), nil
	}
}

func (u usersRegistrationDo) FindByPage(offset int, limit int) (result []*model.UsersRegistration, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u usersRegistrationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u usersRegistrationDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u usersRegistrationDo) Delete(models ...*model.UsersRegistration) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *usersRegistrationDo) withDO(do gen.Dao) *usersRegistrationDo {
	u.DO = *do.(*gen.DO)
	return u
}
