// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdmin = "admin"

// Admin 管理员表
type Admin struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	Username  string    `gorm:"column:username;not null;comment:用户名" json:"username"`                                // 用户名
	Mobile    string    `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`                                    // 手机号
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
