// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsersRegistration = "users_registration"

// UsersRegistration mapped from table <users_registration>
type UsersRegistration struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username     string    `gorm:"column:username;not null" json:"username"`
	PasswordHash string    `gorm:"column:password_hash;not null" json:"password_hash"`
	Email        string    `gorm:"column:email" json:"email"`
	PhoneNumber  string    `gorm:"column:phone_number" json:"phone_number"`
	Role         string    `gorm:"column:role;not null;default:user" json:"role"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UsersRegistration's table name
func (*UsersRegistration) TableName() string {
	return TableNameUsersRegistration
}
